---
functional:
  - Пользователь должен иметь возможность искать товары по ключевому слову или категории
  - Пользователь должен иметь возможность фильтровать товары
  - Пользователь должен иметь возможность просматривать товары и просматривать подробную информацию о товаре
  - Пользователь должен иметь возможность добавлять товары в корзину и просматривать содержимое корзины
  - Пользователь должен иметь возможность переключить язык интерфейса
  - Важно, что бы на странице корзины пользователь cможет удалить товар из корзины, продолжить выбирать товары в каталоге, оформить заказ с переходом на страницу оплаты
non-functional:
  - Сайт должен быть безопасным и защищать данные пользователя
  - Сайт нужно разработать с учетом удобства использования и оптимизировать для скорости работы
  - Сайт должен иметь мобильную версию
  - Сайт нужно протестировать на совместимость с последними версиями браузеров
  - Важно, чтобы сайт мог обрабатывать большое количество трафика
  - Сайт должен быть доступен на различных устройствах
  - Сайт должен иметь локализацию (перевод) на русский и английский языки
  - Сайт должен соответствовать разработанному интерфейсу интернет-магазина с просмотром и фильтрацией товаров, а также добавлением их в корзину
  - На сайте магазина должна быть адаптиваная верстка чтобы он был удобным на мобильных устройствах
  - Важно, что бы SPA-приложение не перегружало страницу магазина
  - Для пользователя на странице товара и в каталоге нужно выводить название, рейтинг, цена со скидкой и без нее
implicit:
  - Пользователь должен иметь возможность отменить выбранную категорию
  - Сайт должен сохранять выбранный язык после обновления страницы
  - Пользователь должен иметь возможность удалить колличество товаров сразу, а не по одному
  - На сайте должны корректно отобраться знаки языков
